var GAME_LEVELS = [
  ["                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
	 "               k                 k             k        k               x",
	 "                                                                        x",
	 "                                              k   k    k  k             x",
	 "           k      k          k     k                                    x",
	 "                                                                        x",
	 "                                                                        x",
	 "                                xxxxxx                                  x",
	 "                                x    x                                  x",
	 "     @                          x    x            s                    ox",
	 "xxxxxxxxxxxxxxx      xxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	 "              x      x                                                   ",
	 "              xoooooox                                                   ",
	 "              xxxxxxxx                                                   ",
	 "                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
     "                                                                         "],
	["                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
	 "                         k                     k                         ",
	 "        k                                                                ",
	 "                                k    k                                  x",
	 "                    k              k                 k                  x",
	 "                  k   k                                                 x",
	 "                                                          k             x",
	 "                                                                        x",
	 "                                                                        x",
	 "                                xxxxxx                  x               x",
	 "                                 oooox                  x               x",
	 "     @                    o      oooox      =   o       x              ox",
	 "xxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
	 "              x!!!!!!x                                                   ",
	 "              x!!!!!!x                                                   ",
	 "              xxxxxxxx                                                   ",
	 "                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
	 "                                                                         ",
     "                                                                         "],
  ["                                                                                ",
   "                                                                  k             ",
   "                                             k            k                     ",
   "                                                                 k  k           ",
   "                             k          k      k     k                          ",
   "             k                                                                  ",
   "           k    k         k      k                                xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                  U                                 x  ",
   "  x  @       x  x                                                xxxxx    s  x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                  k             ",
   "                                             k            k                     ",
   "                                                                 k  k           ",
   "                             k          k      k     k                          ",
   "             k                                                                  ",
   "           k    k         k      k                 xxx      o     xxx           ",
   "                                                   x!x     xx    xx!xx          ",
   "                                             xx    xvx           x!!!x          ",
   "                                             v                   | v            ",
   "                                                                                ",
   "                                                                            xx  ",
   "                                          x                                  x  ",
   "  x                                    xxxx                              x   x  ",
   "  x                                                                        o x  ",
   "  x          xxxx       o                                   |        |       x ",
   "  x  @       x  x                      o                         xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxx!!!xxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                    k                                                                                         ",
   "                                                                                                              ",
   "      k                                             k                                                         ",
   "                                         k                        k                          k                ",
   "                   k       k                                                                                  ",
   "                                                   k                                                          ",
   "                                                           x            x  xxx                                ",
   "       k                                                   xx!=       !xx                                     ",
   "                                         xxx                x          x                                      ",
   "                                          x                 x   oooo   x       xxx                            ",
   "                k       k       k         x                 x          x      x!!!x      k        k           ",
   "                                          x                 xxxxxxxxxxxx       xxx                            ",
   "              k                          xxx      x   x      x                                                ",
   "                                          xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                          x           x                   =x!!!x                              ",
   "                                          x           x                     xxx               k             k ",
   "                                         xxx          x                                                       ",
   "              k                           x= =        x            xxx                      k                 ",
   "                                k         x           x           x!!!x                                       ",
   "                                          x    =     =x     o      xxx       xxx                              ",
   "        k                              xxxxx          x                     x!!!x                             ",
   "                              o   o       x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxxxxxx xxxxxxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x=            x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx        |               xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x        xxxx      xxxx      xxx xxx                             x  ",
   "  x                                o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x                xxx        x    xxx    x                           sx x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "        k                    k                                                  k                 xxxxx       ",
   "                                                           k                  k                   x           ",
   "             k                                                                                    x xxx       ",
   "     k                    o                               k                                       x x x       ",
   "                                          k                                                  o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                    k                    k      x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x       k                                          x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                              k                                                               ",
   "          o              xxx                              xx                                                  ",
   "                          U                                                      k                            ",
   "                                                                  k                             k             ",
   "                                           k          xx                                                      ",
   "        k          xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
